### ISSUE TITLE
deb package 

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#11]
I like how Grafana does it: 

https://grafana.com/grafana/download?platform=linux

just installation from source and everything works

**Comment by jonyrock** [comment]
a nice alternative is to make installation as node for whole server

**Comment by rozetko** [comment]
I'll try to use [fpm](https://github.com/jordansissel/fpm). Seems like exactly what we need.

**Comment by rozetko** [comment]
Actually, I would create not only deb package, but also rpm, like Grafana does

**Comment by jonyrock** [comment]
@rozetko Can I ask you only add a note why you close it

**Comment by rozetko** [comment]
We don't need packages already because we have everything bundled and precompiled in .tar.gz archive
