### ISSUE TITLE
Analytic Unit cache

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#117]
We want to send model for learning and get if improved after

* Create model to store in db
* Send / get from learning

**Comment by jonyrock** [comment]
So each detector can get a cache with trained model and return a new model
![image](https://user-images.githubusercontent.com/1022757/44679847-b9698b00-aa44-11e8-87ee-68b0222e0041.png)

same thing with predict

**Comment by jonyrock** [comment]
![image](https://user-images.githubusercontent.com/1022757/44680101-7360f700-aa45-11e8-930d-65b581c8673a.png)

**Comment by jonyrock** [comment]
![image](https://user-images.githubusercontent.com/1022757/44680237-cf2b8000-aa45-11e8-8180-647264b7587d.png)

**Comment by rozetko** [comment]
Done
