### ISSUE TITLE
Enhancement: add support for arbitrary datasource

### ISSUE THREAD

**Issue by faxm0dem** [hastic/hastic-server#135]
We'd love to try out the tool but our DS is elastic.

**Comment by rozetko** [comment]
Hi, @faxm0dem! We are planning to support Prometheus and Graphite in the nearest future.
After that we'll write a tool to query Grafana datasources by running their compilers from node.js. As soon as we do that - it will be possible to query any datasource.

**Comment by faxm0dem** [comment]
Thanks, I'm looking forward to trying out that feature: the live demo I've seen at Monitorama.eu 2018 was awesome!

**Comment by jonyrock** [comment]
Ok, we support elastic now. Actual datasources list: https://github.com/CorpGlory/grafana-datasource-kit
