### ISSUE TITLE
Datarange sent to models

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#137]
We got `getQueryRangeForLearningBySegments` method which calculates datarange to send to models
Currently, if you label segments next to each other - model wouldn't even see data in your dashboard timerange
We should change this behaviour somehow

**Comment by jonyrock** [comment]
I made a video abou that. I think we need to make algorithm for this.

**Comment by jonyrock** [comment]
![image](https://user-images.githubusercontent.com/1022757/45266220-43135280-b460-11e8-9559-dfb8b6fe91a8.png)

**Comment by jonyrock** [comment]
![image](https://user-images.githubusercontent.com/1022757/45266237-82da3a00-b460-11e8-8e15-e47bfd600bc2.png)

its me
