### ISSUE TITLE
Anti-segments

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#142]
When segment is deleted from plot - it should become "anti-segment"
And prediction should be considered as wrong if it has found segment inside this "anti-segment"

- [x] add `deleted` flag from node.js
- [ ] use it in models

**Comment by jonyrock** [comment]
@rozetko 

* we need to save "anti-serments" from user labeling. Looks there is no code for that in segments_router.updateSegments()

* send anti-segments to analytics. Maybe it can be in `segments` field of payload, but we need to define it

**Comment by jonyrock** [comment]
@rozetko @VargBurz what is the status of this issue?

**Comment by rozetko** [comment]
@rozetko it works but there is no tests for it yet
There is an issue for it https://github.com/hastic/hastic-server/issues/210
So we can close it, I guess
@VargBurz?

**Comment by rozetko** [comment]
@jonyrock it works but there is no tests for it yet
There is an issue for it https://github.com/hastic/hastic-server/issues/210
So we can close it, I guess
@VargBurz?

**Comment by VargBurz** [comment]
@rozetko  Yes, we can close this issue.
