### ISSUE TITLE
Reduce amount of required labeled segments for learning

### ISSUE THREAD

**Issue by sankerust** [hastic/hastic-server#147]
Currently analytics require at least 2 labeled segments to start the learning process.
Only 1 labeled segment should be enough to allow learning.

User feedback.

**Comment by jonyrock** [comment]
@VargBurz can we learn by one labeled segment ?

**Comment by VargBurz** [comment]
ofc, originally, it was one labeled segment for learning

**Comment by jonyrock** [comment]
@VargBurz @rozetko then put 1 instead of 2

**Comment by rozetko** [comment]
Let's use as datarange then `1st segment start - (now - last segment end)` till `now`
