### ISSUE TITLE
Restore hooks API

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#149]
Now all our notification module doesn`t work. 
We need to make again.

**Comment by jonyrock** [comment]
This is where is should be triggered: https://github.com/hastic/hastic-server/blob/4f4b25d9a3d1927b12fc2bee3d756f57d06ef763/server/src/controllers/analytics_controller.ts#L42

And we need to make a new service for web_hooks_service (along with alerts_controller.ts)

**Comment by jonyrock** [comment]
https://github.com/hastic/hastic-server/wiki/Web-hooks

**Comment by rozetko** [comment]
https://developer.github.com/webhooks/
Maybe we can find something useful here
