### ISSUE TITLE
Error: request failed with status code 503

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#189]
Steps to reproduce:
- add influxdb metric
- create analytic unit
- label segments

Expected behaviour:
- predicted segments get labeled

Actual behaviour:
- Error: request failed with status code 503
![image](https://user-images.githubusercontent.com/1989898/46739851-20b46500-ccaa-11e8-8dae-ee34be574319.png)

Server and Grafana are running on the same host

**Comment by jonyrock** [comment]
Is the real author of issue on github? I think the author is @ipalbeniz

**Comment by ipalbeniz** [comment]
Yes, I'm here :)

**Comment by amper43** [comment]
Hi, @ipalbeniz ! Do you start Hastic inside docker?

**Comment by ipalbeniz** [comment]
Hi @amper43! 

Hastic is not running inside docker. I'm using node v8.12.0 + Ubuntu 16.04.5 LTS, following these steps:
```
wget https://github.com/hastic/hastic-server/releases/download/0.2.3-alpha/hastic-server-0.2.3-alpha-node-8.tar.gz
tar -zxvf hastic-server-0.2.3-alpha-node-8.tar.gz
cd hastic-server-0.2.3-alpha/server/dist
node server
```

Same with grafana (v5.2.4), that is not running inside docker.
Hastic-Panel is v0.2.3

**Comment by jonyrock** [comment]
Hey @ipalbeniz , can you please: 
* make steps above
* goto http://localhost:8000 

and send us info from there.

**Comment by ipalbeniz** [comment]
Hi @jonyrock 
Sorry about the delay.
This is what I get when I go to http://localhost:8000 
`{
"server": "OK",
"analyticsReady": true
}`

**Comment by jonyrock** [comment]
@ipalbeniz can we make a google.meet (with screen sharing) with you? so you show us :)
Are you on IRC?

**Comment by rozetko** [comment]
Hey, @ipalbeniz 
Can you please check whether you have `Server` or `Browser` datasource access type?
![image](https://user-images.githubusercontent.com/1989898/48776099-efcf4300-ecdf-11e8-8bc5-2187d259f2ff.png)
If it's not `Server` - hastic-server won't be able to get data from there

**Comment by rozetko** [comment]
Glad to help!
