### ISSUE TITLE
Grafana panel doesn't refresh segments after deletion.

### ISSUE THREAD

**Issue by VargBurz** [hastic/hastic-server#197]
Imagine, that you label few segments in any model, for example, in peaks. This segments fall in fit, after learning and filtration analytics returns supposably 20 peaks. You decide, that 20 peaks is too much and delete 2 segments, after new learning and filtration analitics returns 0 peaks (all was deleted).
But in grafana panel the same 20 peaks will remain.

**Comment by rozetko** [comment]
Already fixed
