### ISSUE TITLE
Specific error messages

### ISSUE THREAD

**Issue by sankerust** [hastic/hastic-server#201]
We should make error messages more detailed.

One of the users pointed out, that error messages currently don't help in finding and fixing an error.

E.g. One of the cases is the `unexpected error` that is being thrown when `HASTIC_SERVER_URL` is unreachable. (both when the server is down and when the variable simply doesn't match the servers url)

**Comment by jonyrock** [comment]
@sankerust I believe that it is a issue for https://github.com/hastic/hastic-grafana-graph-panel

**Comment by rozetko** [comment]
There is already an issue for that: https://github.com/hastic/hastic-grafana-graph-panel/issues/48

**Comment by rozetko** [comment]
e.g. When you have some analytic unit in panel, but don't have it in server - you got `Can't find anything` error
Should be changed to something like `There is no analytic unit with id ${id}`
