### ISSUE TITLE
Workers for AnalyticUnits

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#203]
We need to find a way to launch learning process simultaneously for two different learning tasks. 
Making this task forces us to make workers in python process.

**Comment by jonyrock** [comment]
@amper43 @rozetko lets start research with this link: https://pymotw.com/3/asyncio/executors.html

**Comment by jonyrock** [comment]
@amper43 @rozetko when please describe in free form where you think in code we should place it

**Comment by rozetko** [comment]
@jonyrock seems like there should be a class in `analytic_unit_manager.py` with executor field, waiting for new tasks to come, create workers and run them

**Comment by jonyrock** [comment]
https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading
