### ISSUE TITLE
Learning on creation of pattern from beginning

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#21]
If you make a new pattern with name "drop" and you already have "drop" in database, learning state would start

**Comment by jonyrock** [comment]
Looks like learning always starts. Dont know if it is backend or fraontend.

**Comment by rozetko** [comment]
Oh, I get what you are talking about
It's not a bug though
It's just a moment when server downloading a dataset
Guess, we just need to add another status (like 'Downloading a dataset')

**Comment by jonyrock** [comment]
or `initialization`

**Comment by rozetko** [comment]
Yeah, sounds fine
We should rename issue or create a new one then

**Comment by jonyrock** [comment]
@sankerust check out what happens in worker please
