### ISSUE TITLE
Analytics project structure improvement

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#215]
I think we should rethink our mess with docs/files in analytics. 

I nice start is: https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

**Comment by jonyrock** [comment]
@rozetko I think I also need to check 
* node.js part
* the process of building python bundle of analytics

what else?

**Comment by rozetko** [comment]
- paths in `config.py`
- imports

**Comment by rozetko** [comment]
Done
