### ISSUE TITLE
Processing for 'NaN' values

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#231]
When there is no data for requested segment, returned values fills by 'NaN'. Analytics must processing this case correctly. Offered solution: check that non-NaN data fills segment a least on 10%.

**Comment by amper43** [comment]
@VargBurz please, clarify offered solution

**Comment by VargBurz** [comment]
We have two types of segments: First - the segments labeled by the user, that are then passed to learning process. These have to be completely filled with values(i.e. no NaN values). 
The second type of segments are possible patterns that should be checked for 'NaN's. If there are more than 50% of 'NaN', then this pattern must be deleted. If there are less than 50%, then when this pattern is compared with the common model, and same amount of values is deleted from common model.
