### ISSUE TITLE
Models refactoring

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#237]
There are a lot of repeating code in models
We should take common pieces of code and move them to `utils/` for better structure and testing

**Comment by jonyrock** [comment]
@rozetko @VargBurz can we close this one?

**Comment by jonyrock** [comment]
@rozetko @VargBurz 
I want to see clear DoD or close this issue as not actual

**Comment by rozetko** [comment]
DoD are 2 sub-issues:
- https://github.com/hastic/hastic-server/issues/270
- https://github.com/hastic/hastic-server/issues/271

They are already closed
So we can close this issue
