### ISSUE TITLE
Error: type object 'sklearn.tree...'

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#28]
With usage "General approach", user gets error from python 
like follows:
![image](https://user-images.githubusercontent.com/1022757/41863819-9c427b10-78b0-11e8-8bbe-ec3a2e24443c.png)

**Comment by rozetko** [comment]
Fixed it
It is a common problem when compiling module which has `sklearn` as dependency
Follow link for more info: https://stackoverflow.com/a/30235040

**Comment by jonyrock** [comment]
@rozetko nice one, thank you
