### ISSUE TITLE
Leave only important part of panelUrl

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#288]
Currently all analytic units have a `panelUrl` field (which contains dashboard and panel id)
But we're storing the whole URL
And it can break persistence while moving Grafana instance to another host / protocol

**Comment by rozetko** [comment]
It is a panel bug
Recreated: https://github.com/hastic/hastic-grafana-graph-panel/issues/102

**Comment by jonyrock** [comment]
@rozetko server should validate value then: only _important_ part, nothing else :)
