### ISSUE TITLE
Store only actual analytic units in Data Puller

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#296]
Currently units are added to DataPuller only on unit creation
Thus, when you are restarting server - DataPuller has no units
Maybe we can just get units with `alert === true` from db and push / pull data for them?
@jonyrock @amper43 what do you think?

**Comment by amper43** [comment]
together with that in panel we should get units from server for consistency and avoiding pulling unnecessary data

**Comment by jonyrock** [comment]
@rozetko there is not DataPuller as I know in the master. 

I think it is a bug, but we will not fix it in this release
