### ISSUE TITLE
Data kit error: status code 400

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#300]
When DataPuller tries to query data with the same `from` and `to` fields - Grafana returns error with code 400
![image](https://user-images.githubusercontent.com/1989898/49618834-16bd9280-f9cb-11e8-9afc-1bf3cc764736.png)

**Comment by jonyrock** [comment]
@rozetko @amper43 should we move this issue to https://github.com/CorpGlory/grafana-datasource-kit ?

**Comment by rozetko** [comment]
It's rather Hastic's than data-kit's issue
Though `grafana-datasource-kit` can warn you if you're using equal `from` and `to` in query

**Comment by rozetko** [comment]
Also, this error often occurs in random moments when using Prometheus

**Comment by amper43** [comment]
estimate: 1/8 of day
