### ISSUE TITLE
Peaks detector algorithm improvement

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#34]
- [x] Make it work only after labeling (like drops)
- [x] Make it find peaks similar to labeled
- [ ] Find / create test dataset
- [ ] Write tests

**Comment by jonyrock** [comment]
@rozetko @VargBurz  what is the status of this one?

**Comment by rozetko** [comment]
@VargBurz is integrating it currently

**Comment by rozetko** [comment]
Implemented already
