### ISSUE TITLE
Index transform bug

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#38]
There is a bug when indices get transformed to time
![image](https://user-images.githubusercontent.com/1989898/41990900-6cc64392-7a4c-11e8-9950-4687521b3b67.png)
In this screenshot all segments have the same length in indices, but the one on the left has a lot larger length

**Comment by jonyrock** [comment]
@rozetko I think you are working on something connected with this task

**Comment by rozetko** [comment]
@jonyrock yes, looks close enough, thx

**Comment by rozetko** [comment]
Not actual
