### ISSUE TITLE
More info in webhooks

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#382]
We should send more info in webhooks:
- analytic unit id
- analytic unit type
- panel URL
- etc

@jonyrock @amper43 what do you think?

**Comment by amper43** [comment]
suggest:
* analytic unit name
* time
* value for threshold
* segment's features for patterns (it have sense for automation that will use Hastic)
* may be [image](http://docs.grafana.org/reference/sharing/#direct-link-rendered-image) with detected region
