### ISSUE TITLE
Analytics gets down without any exception

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#407]
Sometimes analytics is down but you can't see exception in logs
It happens during detection for webhooks
Maybe executor thread falls and exception just not logged

**Comment by rozetko** [comment]
P.S. that fix didn't help #400

**Comment by amper43** [comment]
tried to fix this issue in https://github.com/hastic/hastic-server/commit/6b9a4a03cc845b53cdcf5ecf9e501cba0f28f4fd

**Comment by jonyrock** [comment]
@rozetko I close this one
