### ISSUE TITLE
Accept various URL inputs

### ISSUE THREAD

**Issue by sankerust** [hastic/hastic-server#416]
Recently there was an issue, where `GRAFANA_URL` provided by the user was not accepted by hastic, since it had a slash (`/`) at the end of the URL.
`"http://localhost:8000/"`
instead of:
`"http://localhost:8000"`

resulted in this error:
`Data kit: got response 404, message: Request failed with status code 404`

We should figure out a way to accept various URL inputs, to avoid such issues in future.

**Comment by jonyrock** [comment]
I think we can also strip whitespaces from the string
