### ISSUE TITLE
No server info

### ISSUE THREAD

**Issue by sankerust** [hastic/hastic-server#417]
In our release version of server the info about server in `Hastic info` tab is not sent/recieved.

![image](https://user-images.githubusercontent.com/22073083/52793286-73e65c00-307e-11e9-90a5-edfb3cbf08a9.png)

Browser console output:
![image](https://user-images.githubusercontent.com/22073083/52793306-7d6fc400-307e-11e9-8b1c-f7b7d79782f3.png)

```
analytic_service.ts:144 
Uncaught (in promise) TypeError: Cannot read property 'branch' of null
    at AnalyticService.eval (analytic_service.ts:144)
    at step (series_overrides_ctrl.ts:160)
    at Object.eval [as next] (series_overrides_ctrl.ts:160)
    at fulfilled (series_overrides_ctrl.ts:160)
```

**Comment by rozetko** [comment]
Will add it to current release `0.3.0-beta`
