### ISSUE TITLE
Learning on deletion

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#45]
All of your models: drops, peaks, ... don`t give a shit about deletion.

**Comment by jonyrock** [comment]
@rozetko @VargBurz the question is if should we implement "anti-segments" first. 
What do you guys think?

**Comment by rozetko** [comment]
Yes, it would be convenient to implement "anti-segments" first

**Comment by rozetko** [comment]
https://github.com/hastic/hastic-server/issues/142
