### ISSUE TITLE
Error: can't start learning when it's already started

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#491]
This error occurs when clicking "Re-detect all analytic units" from multiple devices at the same time:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1989898/55249243-a9c15780-525c-11e9-9627-a760ae382c09.png">

**Comment by jonyrock** [comment]
What behavior should be correct if we get multiple requests from different devices (sessions)

**Comment by rozetko** [comment]
We should start pulling actual statuses at least
