### ISSUE TITLE
Detection in selected time range 

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#504]
Needed to implement hastic/hastic-grafana-app#235

- `GET /segments`: run detect if there was no detection on given timerange
- split timeseries on processed / non-processed segments
- merge and invalidate segments right

**Comment by rozetko** [comment]
- [ ] Add proxy class for getting segments (which just runs detect)
- [ ] Save queried segments with detection results
- [ ] Merge queried segments
- [ ] Invalidate segments cache
- [ ] Use cache instead of proxying detection call

**Comment by amper43** [comment]
subtask `Save queried segments with detection results` doesn't exist because of we already get segments from data base by time range (see `segments_router.ts`)
