### ISSUE TITLE
Detect thresholds on the whole dataset

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#505]
Currently threshold uses only the last value for detection
It should be executed on the whole dataset

**Comment by jonyrock** [comment]
Can you please define better "whole dataset" here please? 
I can't imagine that you go back to a year ago to search thresholds activation there.

**Comment by rozetko** [comment]
"Whole dataset" means the whole dataset sent to analytics (2x range from 1st segment to `now`)
