### ISSUE TITLE
Support datasources other than InfluxDB

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#60]
Currently only InfluxDB datasource is supported
We should find a way to support other Grafana's datasources

**Comment by jonyrock** [comment]
@rozetko but I thought we can query any datasouce via grafana

**Comment by rozetko** [comment]
@jonyrock We can, but we need to support different request types for each datasource

**Comment by rozetko** [comment]
Datasources support moved to https://github.com/CorpGlory/grafana-datasource-kit
