### ISSUE TITLE
Thresholds error: from is NaN 

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#621]
You get this error any time you click `Apply` on threshold analytic unit
![image](https://user-images.githubusercontent.com/1989898/57039696-005bf000-6c66-11e9-8408-8a36e299bdb6.png)
There was no error before implementing https://github.com/hastic/hastic-server/issues/504

**Comment by jonyrock** [comment]
A bit off top. We have "apply" for threshold, but not for pattern, right?

**Comment by rozetko** [comment]
`Apply` analogue for pattern is labeling save
