### ISSUE TITLE
all_anomalies.json gets rewrited after restart

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#63]
Steps to reproduce:
- create anomaly
- find it in `data/anomalies/all_anomalies.json`
- restart server
- create new anomaly

Now there is only new anomaly in `all_anomalies.json`
It happens because `loadAnomaliesMap()` method doesn't get executed on anomaly insert

**Comment by jonyrock** [comment]
How do you think, maybe we make  https://github.com/hastic/hastic-server/issues/58 
And get rid of all bugs cused by files ?

**Comment by rozetko** [comment]
@jonyrock it would be really convenient
