### ISSUE TITLE
Return version of server 

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#66]
We can face a problem where user has an older version of hastic-panel and we need to return  version of hastic-server.  Also it is necessary for bug reports. 

So we need to 
- [ ] keep track of current version of server with is the same as release 
- [x] return server version when get status (root) url

The first time we get this problem: https://github.com/hastic/hastic-server/pull/65

**Comment by jonyrock** [comment]
we can get it from `package.json`

**Comment by rozetko** [comment]
Guess we can close it
