### ISSUE TITLE
Name for basic anomaly detector type

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#663]
The algorithm we have now won't be changed much. We will set smoothing and confidence.
If we decide, for example, analyze micro changes in metric, then smoothing will hide it so we need another algorithm. 

![image](https://user-images.githubusercontent.com/1022757/57973559-5db8a680-79b3-11e9-918d-183e85787151.png)

@rozetko @amper43 @VargBurz  I encourage you to choose this name wisely.

**Comment by jonyrock** [comment]
We will describe how this algorithm works a lit bit in release notes

**Comment by rozetko** [comment]
Closed via https://github.com/hastic/hastic-server/commit/0d6b4c45cf0606d7e03cb2f186aca7ee2efb8c18
