### ISSUE TITLE
Error: skip detection: data length less than window_size

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#690]
![image](https://user-images.githubusercontent.com/1989898/58875882-555fab80-86d5-11e9-868f-bc5f3a1b01ba.png)

## Steps to reproduce
- set `Last <n> time` as timerange
- create pattern analytic unit
- label something
- wait for detect
- refresh

**Comment by DirkFries** [comment]
Hi @all,

I get the same error in Hastic 0.3.6, but my way to reproduce this is slightly different. In my case I get the error too, if I choose a fixed Timeperiod from 2 dates in the past.

![Hastic](https://user-images.githubusercontent.com/51441256/61460677-82a7a680-a96f-11e9-81f0-77cbf2b0c821.jpg)
