### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Djam36** [hastic/hastic-server#698]
hi,all
i use hastic-server-0.3.5-beta  to label data, but it will return 404, Have you ever encountered a 404 error? 

i see in  hastic server's log message strange url 

Data kit: fail while request data: Request failed with status code 404 query url: "/http://url_prometheus:9090/api/v1/query_range"

is it somehow connected with my problem?
![HasticProblem](https://user-images.githubusercontent.com/18193364/59430022-cd228a00-8de9-11e9-8a28-6a89d6d9e339.png)

**Comment by amper43** [comment]
Hi, @Djam36 

1. Is Access type set to `Server` in datasource settings?
2. Do you have real Prometheus url set for datasource or is it `http://url_prometheus:9090` like in logs
3. Does datasource url start with `/` in datasource tab or `/` is visible only in Hastic-server logs?

**Comment by Djam36** [comment]
> Hi, @Djam36
> 
> 1. Is Access type set to `Server` in datasource settings?
> 2. Do you have real Prometheus url set for datasource or is it `http://url_prometheus:9090` like in logs
> 3. Does datasource url start with `/` in datasource tab or `/` is visible only in Hastic-server logs?

1. Yes, 
2. Yes, i has hidden ulr because of security policy
3. Url start with '/' only in Hastic-server logs

**Comment by amper43** [comment]
@Djam36

Can I ask you to check datasource settings for Prometheus because error seems like Prometheus have access type Browser.
Hastic can query metrics only from datasources (Prometheus, Elastic, etc) that have access type Server.

**Comment by Djam36** [comment]
> @Djam36
> 
> Can I ask you to check datasource settings for **Prometheus**? Error looks like chosen access type is `Browser`. Hastic can query metrics only from datasources with `Server` access type.

Hi, i checked it, realy it is my mistake, sorry
