### ISSUE TITLE
Error: Data kit: fail while request data: Request failed with status code 403

### ISSUE THREAD

**Issue by nadcharin** [hastic/hastic-server#704]
Hi ,
     I'm use hastic-server-0.3.5-beta and try to label data but got error message "Data kit: fail while request data: Request failed with status code 403" when detect the pattern. Is it a grafana issue or hastic-server issue?

![Screen Shot 2562-06-27 at 12 29 13](https://user-images.githubusercontent.com/2987606/60239329-7764dc00-98d7-11e9-9f67-e0f0b922c555.png)

![Screen Shot 2562-06-27 at 12 38 38](https://user-images.githubusercontent.com/2987606/60239712-c8c19b00-98d8-11e9-9319-1c3057ba3ef5.png)

**Comment by jonyrock** [comment]
@nadcharin is this error actual?

**Comment by Stephan3555** [comment]
Running in the same error:

> LEARNING started for mVAxvKvBueGnHxZK                                                                                                                                                                                                                                                                                        
query time range: from Tue May 11 2021 05:52:30 GMT+0000 (UTC) to Tue May 11 2021 11:52:30 GMT+0000 (UTC)                                                                                                                                                                                                                    
Data kit: fail while request data: Request failed with status code 403 query url: "/api/datasources/proxy/13/_msearch"                                                                                                                                                                                                       
Response:         status: 403,         response data: {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Au
thorization=Bearer <REMOVED>"},         headers: {"access-control-allow-origin":"*","content-length":"368","content-type":"application/json","date":"Tue, 11 May 2021 11:52:35 GMT","x-amzn-requestid":"287eca2b-69c5-4ef1-bdba-d374508f54c9","x-c
ontent-type-options":"nosniff","x-frame-options":"deny","x-xss-protection":"1; mode=block","connection":"close"}                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                             

> Error: Data kit: fail while request data: Request failed with status code 403                                                                                                                                                                                                                                                
>     at /var/www/server/dist/server.js:11:166556                                                                                                                                                                                                                                                                              
>     at Generator.next (<anonymous>)                                                                                                                                                                                                                                                                                          
>     at s (/var/www/server/dist/server.js:11:161159)                                                                                                                                                                                                                                                                          
>     at <anonymous> 

Versions:
Hastic-Server: 0.5.1
Hastic-Grafana-Plugin: 0.5.1
Grafana-Version: v7.1.2

Any idea how to solve this?

**Comment by Stephan3555** [comment]
Seems like this error only appears when using Elasticsearch as a datasource. Prometheus works fine
