### ISSUE TITLE
Slack webhook returns 400 missing_text_or_fallback_or_attachments

### ISSUE THREAD

**Issue by xo4n** [hastic/hastic-server#708]
Slack webhook return  **400** _missing_text_or_fallback_or_attachments_. The payload that hastic is sending

```
{
    "meta": {
        "type": "DETECT",
        "analyticUnitType": "ANOMALY",
        "analyticUnitName": "anomaly_booking",
        "analyticUnitId": "f6UQsg09lW0YbOji",
        "grafanaUrl": "http://grafana.trv/d/Tgliz?panelId=86&edit=true&fullscreen=true?orgId=1",
        "from": 1562346000000,
        "to": 1562346000000,
        "message": "2413.743119266055 out of bound"
    },
    "message": "[ANOMALY ALERTING] anomaly_booking\nURL: http://grafana.trv/d/TglViz?panelId=86&edit=true&fullscreen=true?orgId=1\n\nFrom: Fri Jul 05 2019 17:00:00 GMT+0000 (UTC)\nTo: Fri Jul 05 2019 17:00:00 GMT+0000 (UTC)\nID\nSummary: 2413.743119266055 out of bound\nInstance: perf-hastic0"
}
```

The configuration to get the payload is

```
HASTIC_WEBHOOK_URL = "http://httpdump.io/wzqre/"
HASTIC_WEBHOOK_TYPE = "application/json"
HASTIC_WEBHOOK_IMAGE_ENABLED = "true"
```

When replaced ```message```  by ```text``` in the payload, the slack webhook notification works as shown in the image below

{
    "meta": {
        "type": "DETECT",
        "analyticUnitType": "ANOMALY",
        "analyticUnitName": "anomaly_booking",
        "analyticUnitId": "f6UQsg09lW0YbOji",
        "grafanaUrl": "http://grafana.trv/d/Tgliz?panelId=86&edit=true&fullscreen=true?orgId=1",
        "from": 1562346000000,
        "to": 1562346000000,
        "message": "2413.743119266055 out of bound"
    },
    "text": "[ANOMALY ALERTING] anomaly_booking\nURL: http://grafana.trv/d/TglViz?panelId=86&edit=true&fullscreen=true?orgId=1\n\nFrom: Fri Jul 05 2019 17:00:00 GMT+0000 (UTC)\nTo: Fri Jul 05 2019 17:00:00 GMT+0000 (UTC)\nID\nSummary: 2413.743119266055 out of bound\nInstance: perf-hastic0"
}

![hastic_webhook_notification](https://user-images.githubusercontent.com/9038651/60738379-72023400-9f5e-11e9-9bc8-6b92066a6c52.jpg)

**Comment by jonyrock** [comment]
@rozetko says that we can fix this small thing in the code to be able to send messages to Slack. It should not break anything.

@amper43 can you please add link to the code with this logic, please

**Comment by amper43** [comment]
@jonyrock 
https://github.com/hastic/hastic-server/blob/master/server/src/services/alert_service.ts#L28
