### ISSUE TITLE
Cannot set property 'gte' of undefined

### ISSUE THREAD

**Issue by moarpheus** [hastic/hastic-server#715]
Hello guys,

Getting this error with ES source. Please help!

![Screenshot 2019-07-15 at 15 42 23](https://user-images.githubusercontent.com/7750475/61224917-70cbc680-a717-11e9-8c5b-af2a36b57f7d.png)

**Comment by moarpheus** [comment]
Centos 7 macine. ES 6.4, latest Hastic plugin and server.

**Comment by amper43** [comment]
this issue will resolved via https://github.com/CorpGlory/grafana-datasource-kit/issues/80

**Comment by jonyrock** [comment]
@amper43 what is the status of the task?

**Comment by amper43** [comment]
@jonyrock  we can close this issue after release of data-kit
