### ISSUE TITLE
Anomaly detector's segments concatenation

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#716]
We should merge anomaly segments between itself for avoilding follow cases:
![image](https://user-images.githubusercontent.com/5675912/61370271-b06eeb80-a89a-11e9-9196-2968db19409f.png)

**Comment by jonyrock** [comment]
@amper43 please describe the algorithm of merging here. I heard that it's not obvious because of aggregations and etc.

**Comment by rozetko** [comment]
Closed in https://github.com/hastic/hastic-server/pull/741
