### ISSUE TITLE
Error: Cannot read property 'data' of null

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#739]
We should check that `data` is not `null` here
https://github.com/hastic/hastic-server/blob/master/server/src/models/analytic_unit_cache_model.ts#L36

`data` contains cache, it is a responce from DB
Data will be null if analytic unit hasn't got though "learning" stage

**Comment by jonyrock** [comment]
@amper43 please explain 
* what kind of data is `data` ? How have got it?
* when this `data` can be `null`

**Comment by amper43** [comment]
@jonyrock description updated
