### ISSUE TITLE
Anomaly detector: detection re-running in inspect mode

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#757]
Steps to reproduce:
- create `Anomaly` analytic unit
- `Apply`
- enable `Inspect mode`

Behavior:
- analytic unit status jumps from `LEARNING` to `DETECTION` infinitely

Expected behavior:
- analytic unit status is `READY`, detections and HSR are displayed

**Comment by jonyrock** [comment]
@rozetko @amper43 please explain why is it a hastic-server problem, not hastic-app

**Comment by rozetko** [comment]
Panel just re-queries server to get detection-spans' status if it's not `READY`. Server shouldn't re-run detection if it's already running or done.
