### ISSUE TITLE
Analytic: memory and CPU utilization

### ISSUE THREAD

**Issue by amper43** [hastic/hastic-server#825]
Hastic can works with enabled webhooks about 2 days. In this 2 days analytics hog a lot of memory and CPU and drop down.

**Comment by jonyrock** [comment]
@rozetko is it actual? I've heard that after the websockets situation improved

**Comment by jonyrock** [comment]
if it's actual, then it should be moved to https://github.com/hastic/analytics

**Comment by rozetko** [comment]
websockets usage solved this problem

**Comment by jonyrock** [comment]
@rozetko should we close the issue then?
