### ISSUE TITLE
correct error handling in exitHandler

### ISSUE THREAD

**Issue by jonyrock-back** [hastic/hastic-server#853]
this is how `PrcessService.exitHandler` looks like:

```js
function exitHandler(options: any, err?: any) {
  if(exitHandled) {
    return;
  }
  exitHandled = true;
  for(let i = 0; i < exitHandlers.length; i++) {
    exitHandlers[i]();
  }
  console.log('process exit');
  process.exit();
}
```

the problem here is that if any of handlers throw an exception, then all other will not be executed. 
It should be much more robust if we catch exceptions and log about that

**Comment by rozetko** [comment]
closed via https://github.com/hastic/hastic-server/commit/09788eb0dd891647a08c884aaab9c30b9f549c07
