### ISSUE TITLE
Analytic in background?

### ISSUE THREAD

**Issue by tuapuikia** [hastic/hastic-server#877]
Hi,

I would like to know how to run the analytic task in the background. I realize after I close the grafana page, learning and analytic stopped. Is it possible to run analytic in the background based on rule/metric defined in hastic-server?

Below is the message I get after I close my grafana page. New data is not being processed.

```hastic-server-0 hastic-server got detection result for E6m4sAG7pxx1Cwol with 57 segments
hastic-server-0 hastic-server query time range: from Sat Mar 07 2020 06:14:18 GMT+0000 (UTC) to Sat Mar 07 2020 06:23:12 GMT+0000 (UTC)
hastic-server-0 hastic-server query time range: from Sat Mar 07 2020 06:41:12 GMT+0000 (UTC) to Sat Mar 07 2020 06:48:00 GMT+0000 (UTC)
hastic-server-0 hastic-server run task, id:E6m4sAG7pxx1Cwol
hastic-server-0 hastic-server got detection result for E6m4sAG7pxx1Cwol with 8 segments
hastic-server-0 hastic-server run task, id:E6m4sAG7pxx1Cwol
hastic-server-0 hastic-server got detection result for E6m4sAG7pxx1Cwol with 21 segments
```

**Comment by jonyrock-back** [comment]
Hi @tuapuikia 

When you "close" Grafana, you mean you stop it it's process or close browser? 
If first case hastic can't work yet because it fetches data through Granafa, it second case everything should be alright.

**Comment by tuapuikia** [comment]
ok, found the problem why analytic is not running in the background. I need to enable notification to trigger the background processing. :+1:
