### ISSUE TITLE
Detections in the future

### ISSUE THREAD

**Issue by rozetko** [hastic/hastic-server#888]
Let's say you have daily data for the whole year and you want to know if there will be a detection in 2 weeks. You won't get any detections.

Possible reasons:
- there may be some code in the node part which doesn't allow to query data after `now`

**Comment by jonyrock** [comment]
We need to resolve this https://github.com/hastic/hastic-server/issues/925 first

**Comment by rozetko** [comment]
This issue is not actual anymore
I'm testing it with threshold detector and it works fine: I'm getting alerts for events that will occur in 2 weeks
