### ISSUE TITLE
Connection Call Failed when trying to execute hastic-analystics in Docker

### ISSUE THREAD

**Issue by qianvera** [hastic/hastic-server#889]
Hello!

I'm trying to install the hastic app in Grafana. I followed the official installation tutorial, but still cannot start hastic in Grafana web. The Grafana web shows cannot access to hastic info, which might be caused by the failed connection between server and Grafana. But I am not sure.

Hastic-analystics, hastic-server and grafana are installed in three Docker containers separately. 

1. Environment
    Ubuntu 18.04
2. Grafana v6.7.2
    Port: 0.0.0.0:3000->3000/tcp
    corpglory-hastic-app-0.3.9 installed in `/var/lib/grafana/plugins/`.
3. Hastic-analystics
    docker run -d --name hastic-analytics -p 8002:8002 hastic/analytics
    Port: 0.0.0.0:8002->8002/tcp
4. Hastic-server 
    docker run -d \
  --name hastic-server \
  -p 8000:8000 \
  -e HASTIC_API_KEY=`<my api key>` \
  -e ZMQ_CONNECTION_STRING=tcp://127.0.0.1:8002\
  -v /some/host/path:/var/www/data \
  hastic/server
    Port: 0.0.0.0:8000->8000/tcp
5. Problem
The Grafana web shows cannot access to panel and hastic info. And when I try to execute hastic-analystics in Docker using `docker exec -it hastic-analytics python -u bin/server`, it returns faill as shown below.
![image](https://user-images.githubusercontent.com/13497279/79581944-b0d43580-80fd-11ea-93ed-6f1fe44a3509.png)

Do you know how to solve this problem?
Thank you very much!

**Comment by qianvera** [comment]
When Hastic-analystics, hastic-server and grafana are installed in three Docker containers, ip address should be Gateway ip. ZMQ_CONNECTION_STRING=tcp://172.17.0.1:8002.

**Comment by jonyrock** [comment]
@qianvera thanks
