### ISSUE TITLE
Fix known-issues 

### ISSUE THREAD

**Issue by jonyrock** [hastic/hastic-server#9]
I think we should rethink this part: https://github.com/hastic/hastic-server#known-bugs--issues

Let's check what is actual and make issues here on github if we have bugs.

**Comment by rozetko** [comment]
Bugs from this part are still actual
Associated issues:
- Adding labeled segments while learning is in progress is not supported (https://github.com/hastic/hastic-server/issues/55)
- Dataset doesn't update after 1st learning (https://github.com/hastic/hastic-server/issues/61)
- Currently only influxDB datasource is supported (https://github.com/hastic/hastic-server/issues/60)

Guess we can change this part's content to just [opened bug issues](https://github.com/hastic/hastic-server/issues?q=is%3Aissue+is%3Aopen+label%3Abug)?

**Comment by rozetko** [comment]
@jonyrock Let's change this part's content to just [open bug issues](https://github.com/hastic/hastic-server/issues?q=is%3Aissue+is%3Aopen+label%3Abug)?

**Comment by jonyrock** [comment]
@rozetko so close this issue cuz we have documented bugs in issues?

**Comment by rozetko** [comment]
Yeah, let's close it
