### ISSUE TITLE
analytics Ready false issue

### ISSUE THREAD

**Issue by petrk94** [hastic/hastic-server#90]
Hello,

Im facing after installing and running the hastic-server, the issue, that I dont get it working.

This is what I get when starting the hastic-server with npm start:
```
root@hasticio:~/hastic-server/server# npm start

> hastic-server@0.1.4-alpha start /root/hastic-server/server
> node dist/server.js

Creating analytics process...
python3 server.py
/root/hastic-server/analytics
Server is running on :8080
Can`t run analytics process: Traceback (most recent call last):
  File "server.py", line 7, in <module>
    import services
  File "/root/hastic-server/analytics/services/__init__.py", line 1, in <module>
    from services.server_service import ServerService
  File "/root/hastic-server/analytics/services/server_service.py", line 3, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
```

This is what I get when I open the IP and port in browser
`{"server":"Ok","analyticsReady":false,"version":"0.1.4-alpha"}
`
I use a config file, Port is set 8080; API from Grafana is even set and the third value I dont have changed.

Now I dont know whats wrong, due I can not a manual or step by step tutorial explaining.

I hope you can help
Thanks

**Comment by rozetko** [comment]
Hey, @petrk94! Did you install python dependencies by typing ```pip3 install -r requirements.txt``` in `analytics/` directory?
BTW, what is your python version? Do you have `python3` binary in PATH?

**Comment by petrk94** [comment]
No, I didnt made it, can you update the installation way?
https://github.com/hastic/hastic-server#installation

I already wondered that its not working how its in the code shown.
I will check that again and tell you here if I see a change

**Comment by petrk94** [comment]
@rozetko 
ok, I have it running now:

```
root@hasticio:~/hastic-server/server# npm start

> hastic-server@0.1.4-alpha start /root/hastic-server/server
> node dist/server.js

Creating analytics process...
python3 server.py
/root/hastic-server/analytics
Server is running on :8080
Ok, pid: 10021
Binding to zmq...: ipc:///tmp/hastic/8080
Ok
Start analytics pinger...
Ok
```

But I still get the analytics ready false:
`{"server":"Ok","analyticsReady":false,"version":"0.1.4-alpha"}`

**Comment by jonyrock** [comment]
@petrk94 I am sorry than you experiencing problems with start. 
Have you tried to wait a bit for analytics process to start? 
The idea is that a new python process (`analytics/server.py`) started from `npm start` and it tries to connect back to node.js process. 

So in log you should see something like "Analytics is up"

I will test it in 3 hours and try to find what might be wrong.

**Comment by sankerust** [comment]
Hello @petrk94 !
Are you using WSL for windows by any chance?

If so - please check the task manager for background processes called ```python3.5```

Kill all running instances of python3.5 processes and try to start the server again.

Please let us know, if it works or not.

**Comment by jonyrock** [comment]
@petrk94 it is a bug. We are fixing it: https://github.com/hastic/hastic-server/issues/91

**Comment by petrk94** [comment]
@jonyrock ah ok I understand :)
now problem, its still a alpha^^.
I even dont know how to use it correctly with Grafana, due I have no experience in it

**Comment by jonyrock** [comment]
@petrk94  thats fine:) 
Will you come over if we make a forum where you can ask questions? 
Say, as https://community.grafana.com/

**Comment by petrk94** [comment]
@jonyrock 
yes sure, Im interest in learning how to get grafana connected with data and to get it with hastic.io analyzed :) 
Thanks

**Comment by rozetko** [comment]
Hey, @petrk94! We've fixed this bug
You can do `git pull` and try to run it again
